const songs = [
  {
    author: "Ed Sheeran",
    name: "Shape Of You",
    content: [
      [
        { lyrics: "The" },
        { lyrics: "club", chords: "C" },
        { lyrics: "isn't" },
        { lyrics: "the" },
        { lyrics: "best", chords: "G" },
        { lyrics: "place" },
        { lyrics: "to" },
        { lyrics: "find" },
        { lyrics: "a" },
        { lyrics: "lover", chords: "Am" },
      ],
      [
        { lyrics: "So" },
        { lyrics: "the" },
        { lyrics: "bar", chords: "F" },
        { lyrics: "is" },
        { lyrics: "where" },
        { lyrics: "I", chords: "Dm" },
        { lyrics: "go" },
      ],
      [
        { lyrics: "Me" },
        { lyrics: "and" },
        { lyrics: "my", chords: "Em" },
        { lyrics: "friends" },
        { lyrics: "at" },
        { lyrics: "the" },
        { lyrics: "table", chords: "G" },
        { lyrics: "doing" },
        { lyrics: "shots" },
      ],
      [
        { lyrics: "Drinking" },
        { lyrics: "fast", chords: "C" },
        { lyrics: "and" },
        { lyrics: "then" },
        { lyrics: "we" },
        { lyrics: "talk", chords: "Am" },
        { lyrics: "slow" },
      ],
      [
        { lyrics: "Come" },
        { lyrics: "over", chords: "F" },
        { lyrics: "and" },
        { lyrics: "start" },
        { lyrics: "up" },
        { lyrics: "a" },
        { lyrics: "conversation", chords: "G" },
        { lyrics: "with" },
        { lyrics: "just" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "And", chords: "Dm" },
        { lyrics: "trust" },
        { lyrics: "me" },
        { lyrics: "I'll", chords: "C" },
        { lyrics: "give" },
        { lyrics: "it" },
        { lyrics: "a" },
        { lyrics: "chance" },
        { lyrics: "now" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "my", chords: "G" },
        { lyrics: "hand" },
        { lyrics: "stop", chords: "F" },
        { lyrics: "put" },
        { lyrics: "Van" },
        { lyrics: "the", chords: "Em" },
        { lyrics: "Man" },
        { lyrics: "on" },
        { lyrics: "the" },
        { lyrics: "jukebox" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "then" },
        { lyrics: "we", chords: "C" },
        { lyrics: "start" },
        { lyrics: "to" },
        { lyrics: "dance", chords: "Am" },
        { lyrics: "and" },
        { lyrics: "now", chords: "F" },
        { lyrics: "I'm" },
        { lyrics: "singing" },
        { lyrics: "like" },
      ],
      [
        { lyrics: "Girl" },
        { lyrics: "you" },
        { lyrics: "know", chords: "G" },
        { lyrics: "I" },
        { lyrics: "want" },
        { lyrics: "your" },
        { lyrics: "love", chords: "Am" },
      ],
      [
        { lyrics: "Your" },
        { lyrics: "love" },
        { lyrics: "was" },
        { lyrics: "handmade", chords: "Dm" },
        { lyrics: "for" },
        { lyrics: "somebody" },
        { lyrics: "like" },
        { lyrics: "me", chords: "C" },
      ],
      [
        { lyrics: "Come", chords: "G" },
        { lyrics: "on" },
        { lyrics: "now" },
        { lyrics: "follow", chords: "F" },
        { lyrics: "my" },
        { lyrics: "lead" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "may" },
        { lyrics: "be", chords: "Am" },
        { lyrics: "crazy" },
        { lyrics: "don't" },
        { lyrics: "mind", chords: "C" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "Say", chords: "F" },
        { lyrics: "boy" },
        { lyrics: "let's" },
        { lyrics: "not" },
        { lyrics: "talk", chords: "G" },
        { lyrics: "too" },
        { lyrics: "much" },
      ],
      [
        { lyrics: "Grab" },
        { lyrics: "on" },
        { lyrics: "my", chords: "Dm" },
        { lyrics: "waist" },
        { lyrics: "and" },
        { lyrics: "put" },
        { lyrics: "that", chords: "C" },
        { lyrics: "body" },
        { lyrics: "on" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "Come" },
        { lyrics: "on" },
        { lyrics: "now" },
        { lyrics: "follow", chords: "G" },
        { lyrics: "my" },
        { lyrics: "lead" },
      ],
      [
        { lyrics: "Come" },
        { lyrics: "come" },
        { lyrics: "on" },
        { lyrics: "now", chords: "F" },
        { lyrics: "follow" },
        { lyrics: "my", chords: "Am" },
        { lyrics: "lead" },
      ],
      [
        { lyrics: "I'm" },
        { lyrics: "in", chords: "C" },
        { lyrics: "love" },
        { lyrics: "with" },
        { lyrics: "the", chords: "Dm" },
        { lyrics: "shape" },
        { lyrics: "of", chords: "G" },
        { lyrics: "you" },
      ],
      [
        { lyrics: "We", chords: "F" },
        { lyrics: "push" },
        { lyrics: "and" },
        { lyrics: "pull", chords: "Am" },
        { lyrics: "like" },
        { lyrics: "a", chords: "C" },
        { lyrics: "magnet" },
        { lyrics: "do" },
      ],
      [
        { lyrics: "Although" },
        { lyrics: "my", chords: "G" },
        { lyrics: "heart" },
        { lyrics: "is" },
        { lyrics: "falling", chords: "F" },
        { lyrics: "too" },
      ],
      [
        { lyrics: "I'm", chords: "Dm" },
        { lyrics: "in" },
        { lyrics: "love" },
        { lyrics: "with", chords: "C" },
        { lyrics: "your" },
        { lyrics: "body" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "last", chords: "F" },
        { lyrics: "night" },
        { lyrics: "you", chords: "Am" },
        { lyrics: "were" },
        { lyrics: "in" },
        { lyrics: "my" },
        { lyrics: "room" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now" },
        { lyrics: "my", chords: "G" },
        { lyrics: "bedsheets" },
        { lyrics: "smell", chords: "Dm" },
        { lyrics: "like" },
        { lyrics: "you" },
      ],
      [
        { lyrics: "Every", chords: "C" },
        { lyrics: "day" },
        { lyrics: "discovering", chords: "F" },
        { lyrics: "something" },
        { lyrics: "brand", chords: "Am" },
        { lyrics: "new" },
      ],
      [
        { lyrics: "I'm" },
        { lyrics: "in", chords: "G" },
        { lyrics: "love" },
        { lyrics: "with", chords: "C" },
        { lyrics: "your" },
        { lyrics: "body" },
      ],
    ],
  },
  {
    author: "Tones",
    name: "Dance Monkey",
    content: [
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "C" },
        { lyrics: "oh", chords: "Am" },
        { lyrics: "my" },
        { lyrics: "God" },
        { lyrics: "I" },
        { lyrics: "see", chords: "F" },
        { lyrics: "the" },
        { lyrics: "way", chords: "G" },
        { lyrics: "you" },
        { lyrics: "shine" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "your", chords: "Em" },
        { lyrics: "hand" },
        { lyrics: "my" },
        { lyrics: "dear" },
        { lyrics: "and", chords: "C" },
        { lyrics: "place" },
        { lyrics: "them" },
        { lyrics: "both" },
        { lyrics: "in", chords: "Am" },
        { lyrics: "mine" },
      ],
      [
        { lyrics: "You" },
        { lyrics: "know", chords: "F" },
        { lyrics: "you" },
        { lyrics: "stopped", chords: "G" },
        { lyrics: "me" },
        { lyrics: "dead" },
        { lyrics: "while" },
        { lyrics: "I" },
        { lyrics: "was" },
        { lyrics: "passing", chords: "C" },
        { lyrics: "by" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to", chords: "F" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "dance", chords: "G" },
        { lyrics: "just" },
        { lyrics: "one" },
        { lyrics: "more", chords: "C" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "Ooh", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "see" },
        { lyrics: "you", chords: "F" },
        { lyrics: "see", chords: "C" },
        { lyrics: "you" },
        { lyrics: "every" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "And", chords: "G" },
        { lyrics: "oh" },
        { lyrics: "my" },
        { lyrics: "I", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "I" },
        { lyrics: "like" },
        { lyrics: "your" },
        { lyrics: "style", chords: "F" },
      ],
      [
        { lyrics: "You", chords: "C" },
        { lyrics: "you" },
        { lyrics: "make", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "make", chords: "G" },
        { lyrics: "me" },
        { lyrics: "make", chords: "F" },
        { lyrics: "me" },
        { lyrics: "wanna" },
        { lyrics: "cry" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "C" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "dance" },
        { lyrics: "just", chords: "F" },
        { lyrics: "one" },
        { lyrics: "more" },
        { lyrics: "time", chords: "G" },
      ],
      [{ lyrics: "So", chords: "C" }, { lyrics: "they" }, { lyrics: "say" }],
      [
        { lyrics: '"Dance' },
        { lyrics: "for", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "dance" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "oh-oh", chords: "G" },
      ],
      [
        { lyrics: "I've" },
        { lyrics: "never", chords: "C" },
        { lyrics: "seen" },
        { lyrics: "anybody", chords: "Am" },
        { lyrics: "do" },
        { lyrics: "the" },
        { lyrics: "things" },
        { lyrics: "you" },
        { lyrics: "do", chords: "F" },
        { lyrics: "before" },
      ],
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "G" },
        { lyrics: '"Move' },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for", chords: "C" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for" },
        { lyrics: "me", chords: "Am" },
        { lyrics: "ay-ay" },
      ],
      [
        { lyrics: "And", chords: "F" },
        { lyrics: "when" },
        { lyrics: "you're", chords: "G" },
        { lyrics: "done" },
        { lyrics: "I'll" },
        { lyrics: "make" },
        { lyrics: "you" },
        { lyrics: "do" },
        { lyrics: "it", chords: "C" },
        { lyrics: "all" },
        { lyrics: "again" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "said", chords: "Am" },
        { lyrics: '"Oh' },
        { lyrics: "my" },
        { lyrics: "God" },
        { lyrics: "I", chords: "F" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "walking" },
        { lyrics: "by", chords: "G" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "my" },
        { lyrics: "hands", chords: "C" },
        { lyrics: "my" },
        { lyrics: "dear" },
        { lyrics: "and", chords: "Am" },
        { lyrics: "look" },
        { lyrics: "me" },
        { lyrics: "in" },
        { lyrics: "my", chords: "F" },
        { lyrics: "eyes" },
      ],
      [
        { lyrics: "Just" },
        { lyrics: "like", chords: "G" },
        { lyrics: "a" },
        { lyrics: "monkey" },
        { lyrics: "I've", chords: "C" },
        { lyrics: "been" },
        { lyrics: "dancing" },
        { lyrics: "my" },
        { lyrics: "whole", chords: "Am" },
        { lyrics: "life" },
      ],
      [
        { lyrics: "But" },
        { lyrics: "you" },
        { lyrics: "just", chords: "F" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see", chords: "G" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "C" },
        { lyrics: "just" },
        { lyrics: "one", chords: "Am" },
        { lyrics: "more" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "Ooh" },
        { lyrics: "I" },
        { lyrics: "see", chords: "F" },
        { lyrics: "you" },
        { lyrics: "see" },
        { lyrics: "you", chords: "G" },
        { lyrics: "see", chords: "C" },
        { lyrics: "you" },
        { lyrics: "every", chords: "Am" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "oh" },
        { lyrics: "my" },
        { lyrics: "I", chords: "F" },
        { lyrics: "I" },
        { lyrics: "I", chords: "G" },
        { lyrics: "like" },
        { lyrics: "your", chords: "C" },
        { lyrics: "style" },
      ],
      [
        { lyrics: "You", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "make" },
        { lyrics: "me" },
        { lyrics: "make", chords: "F" },
        { lyrics: "me" },
        { lyrics: "make", chords: "G" },
        { lyrics: "me" },
        { lyrics: "wanna" },
        { lyrics: "cry", chords: "C" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "just" },
        { lyrics: "one", chords: "G" },
        { lyrics: "more" },
        { lyrics: "time" },
      ],
      [{ lyrics: "So", chords: "C" }, { lyrics: "they" }, { lyrics: "say" }],
      [
        { lyrics: '"Dance' },
        { lyrics: "for", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "dance" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "oh-oh", chords: "G" },
      ],
      [
        { lyrics: "I've", chords: "C" },
        { lyrics: "never" },
        { lyrics: "seen", chords: "Am" },
        { lyrics: "anybody" },
        { lyrics: "do" },
        { lyrics: "the" },
        { lyrics: "things" },
        { lyrics: "you", chords: "F" },
        { lyrics: "do" },
        { lyrics: "before" },
      ],
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "G" },
        { lyrics: '"Move' },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for", chords: "C" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for" },
        { lyrics: "me", chords: "Am" },
        { lyrics: "ay-ay" },
      ],
      [
        { lyrics: "And", chords: "F" },
        { lyrics: "when" },
        { lyrics: "you're", chords: "G" },
        { lyrics: "done" },
        { lyrics: "I'll" },
        { lyrics: "make" },
        { lyrics: "you" },
        { lyrics: "do" },
        { lyrics: "it", chords: "C" },
        { lyrics: "all" },
        { lyrics: "again" },
      ],
    ],
  },
  {
    author: "Drake",
    name: "One Dance",
    content: [
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "C" },
        { lyrics: "oh", chords: "Am" },
        { lyrics: "my" },
        { lyrics: "God" },
        { lyrics: "I" },
        { lyrics: "see", chords: "F" },
        { lyrics: "the" },
        { lyrics: "way", chords: "G" },
        { lyrics: "you" },
        { lyrics: "shine" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "your", chords: "Em" },
        { lyrics: "hand" },
        { lyrics: "my" },
        { lyrics: "dear" },
        { lyrics: "and", chords: "C" },
        { lyrics: "place" },
        { lyrics: "them" },
        { lyrics: "both" },
        { lyrics: "in", chords: "Am" },
        { lyrics: "mine" },
      ],
      [
        { lyrics: "You" },
        { lyrics: "know", chords: "F" },
        { lyrics: "you" },
        { lyrics: "stopped", chords: "G" },
        { lyrics: "me" },
        { lyrics: "dead" },
        { lyrics: "while" },
        { lyrics: "I" },
        { lyrics: "was" },
        { lyrics: "passing", chords: "C" },
        { lyrics: "by" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to", chords: "F" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "dance", chords: "G" },
        { lyrics: "just" },
        { lyrics: "one" },
        { lyrics: "more", chords: "C" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "Ooh", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "see" },
        { lyrics: "you", chords: "F" },
        { lyrics: "see", chords: "C" },
        { lyrics: "you" },
        { lyrics: "every" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "And", chords: "G" },
        { lyrics: "oh" },
        { lyrics: "my" },
        { lyrics: "I", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "I" },
        { lyrics: "like" },
        { lyrics: "your" },
        { lyrics: "style", chords: "F" },
      ],
      [
        { lyrics: "You", chords: "C" },
        { lyrics: "you" },
        { lyrics: "make", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "make", chords: "G" },
        { lyrics: "me" },
        { lyrics: "make", chords: "F" },
        { lyrics: "me" },
        { lyrics: "wanna" },
        { lyrics: "cry" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "C" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "dance" },
        { lyrics: "just", chords: "F" },
        { lyrics: "one" },
        { lyrics: "more" },
        { lyrics: "time", chords: "G" },
      ],
      [{ lyrics: "So", chords: "C" }, { lyrics: "they" }, { lyrics: "say" }],
      [
        { lyrics: '"Dance' },
        { lyrics: "for", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "dance" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "oh-oh", chords: "G" },
      ],
      [
        { lyrics: "I've" },
        { lyrics: "never", chords: "C" },
        { lyrics: "seen" },
        { lyrics: "anybody", chords: "Am" },
        { lyrics: "do" },
        { lyrics: "the" },
        { lyrics: "things" },
        { lyrics: "you" },
        { lyrics: "do", chords: "F" },
        { lyrics: "before" },
      ],
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "G" },
        { lyrics: '"Move' },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for", chords: "C" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for" },
        { lyrics: "me", chords: "Am" },
        { lyrics: "ay-ay" },
      ],
      [
        { lyrics: "And", chords: "F" },
        { lyrics: "when" },
        { lyrics: "you're", chords: "G" },
        { lyrics: "done" },
        { lyrics: "I'll" },
        { lyrics: "make" },
        { lyrics: "you" },
        { lyrics: "do" },
        { lyrics: "it", chords: "C" },
        { lyrics: "all" },
        { lyrics: "again" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "said", chords: "Am" },
        { lyrics: '"Oh' },
        { lyrics: "my" },
        { lyrics: "God" },
        { lyrics: "I", chords: "F" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "walking" },
        { lyrics: "by", chords: "G" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "my" },
        { lyrics: "hands", chords: "C" },
        { lyrics: "my" },
        { lyrics: "dear" },
        { lyrics: "and", chords: "Am" },
        { lyrics: "look" },
        { lyrics: "me" },
        { lyrics: "in" },
        { lyrics: "my", chords: "F" },
        { lyrics: "eyes" },
      ],
      [
        { lyrics: "Just" },
        { lyrics: "like", chords: "G" },
        { lyrics: "a" },
        { lyrics: "monkey" },
        { lyrics: "I've", chords: "C" },
        { lyrics: "been" },
        { lyrics: "dancing" },
        { lyrics: "my" },
        { lyrics: "whole", chords: "Am" },
        { lyrics: "life" },
      ],
      [
        { lyrics: "But" },
        { lyrics: "you" },
        { lyrics: "just", chords: "F" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see", chords: "G" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "C" },
        { lyrics: "just" },
        { lyrics: "one", chords: "Am" },
        { lyrics: "more" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "Ooh" },
        { lyrics: "I" },
        { lyrics: "see", chords: "F" },
        { lyrics: "you" },
        { lyrics: "see" },
        { lyrics: "you", chords: "G" },
        { lyrics: "see", chords: "C" },
        { lyrics: "you" },
        { lyrics: "every", chords: "Am" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "oh" },
        { lyrics: "my" },
        { lyrics: "I", chords: "F" },
        { lyrics: "I" },
        { lyrics: "I", chords: "G" },
        { lyrics: "like" },
        { lyrics: "your", chords: "C" },
        { lyrics: "style" },
      ],
      [
        { lyrics: "You", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "make" },
        { lyrics: "me" },
        { lyrics: "make", chords: "F" },
        { lyrics: "me" },
        { lyrics: "make", chords: "G" },
        { lyrics: "me" },
        { lyrics: "wanna" },
        { lyrics: "cry", chords: "C" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "just" },
        { lyrics: "one", chords: "G" },
        { lyrics: "more" },
        { lyrics: "time" },
      ],
      [{ lyrics: "So", chords: "C" }, { lyrics: "they" }, { lyrics: "say" }],
      [
        { lyrics: '"Dance' },
        { lyrics: "for", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "dance" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "oh-oh", chords: "G" },
      ],
      [
        { lyrics: "I've", chords: "C" },
        { lyrics: "never" },
        { lyrics: "seen", chords: "Am" },
        { lyrics: "anybody" },
        { lyrics: "do" },
        { lyrics: "the" },
        { lyrics: "things" },
        { lyrics: "you", chords: "F" },
        { lyrics: "do" },
        { lyrics: "before" },
      ],
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "G" },
        { lyrics: '"Move' },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for", chords: "C" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for" },
        { lyrics: "me", chords: "Am" },
        { lyrics: "ay-ay" },
      ],
      [
        { lyrics: "And", chords: "F" },
        { lyrics: "when" },
        { lyrics: "you're", chords: "G" },
        { lyrics: "done" },
        { lyrics: "I'll" },
        { lyrics: "make" },
        { lyrics: "you" },
        { lyrics: "do" },
        { lyrics: "it", chords: "C" },
        { lyrics: "all" },
        { lyrics: "again" },
      ],
    ],
  },
];

export default songs;
