const songs = [
  {
    author: "Ed Sheeran",
    name: "Shape Of You",
    content: [
      [
        { lyrics: "The" },
        { lyrics: "club", chords: "C" },
        { lyrics: "isn't" },
        { lyrics: "the" },
        { lyrics: "best", chords: "G" },
        { lyrics: "place" },
        { lyrics: "to" },
        { lyrics: "find" },
        { lyrics: "a" },
        { lyrics: "lover", chords: "Am" },
      ],
      [
        { lyrics: "So" },
        { lyrics: "the" },
        { lyrics: "bar", chords: "F" },
        { lyrics: "is" },
        { lyrics: "where" },
        { lyrics: "I", chords: "Dm" },
        { lyrics: "go" },
      ],
      [
        { lyrics: "Me" },
        { lyrics: "and" },
        { lyrics: "my", chords: "Em" },
        { lyrics: "friends" },
        { lyrics: "at" },
        { lyrics: "the" },
        { lyrics: "table", chords: "G" },
        { lyrics: "doing" },
        { lyrics: "shots" },
      ],
      [
        { lyrics: "Drinking" },
        { lyrics: "fast", chords: "C" },
        { lyrics: "and" },
        { lyrics: "then" },
        { lyrics: "we" },
        { lyrics: "talk", chords: "Am" },
        { lyrics: "slow" },
      ],
      [
        { lyrics: "Come" },
        { lyrics: "over", chords: "F" },
        { lyrics: "and" },
        { lyrics: "start" },
        { lyrics: "up" },
        { lyrics: "a" },
        { lyrics: "conversation", chords: "G" },
        { lyrics: "with" },
        { lyrics: "just" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "And", chords: "Dm" },
        { lyrics: "trust" },
        { lyrics: "me" },
        { lyrics: "I'll", chords: "C" },
        { lyrics: "give" },
        { lyrics: "it" },
        { lyrics: "a" },
        { lyrics: "chance" },
        { lyrics: "now" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "my", chords: "G" },
        { lyrics: "hand" },
        { lyrics: "stop", chords: "F" },
        { lyrics: "put" },
        { lyrics: "Van" },
        { lyrics: "the", chords: "Em" },
        { lyrics: "Man" },
        { lyrics: "on" },
        { lyrics: "the" },
        { lyrics: "jukebox" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "then" },
        { lyrics: "we", chords: "C" },
        { lyrics: "start" },
        { lyrics: "to" },
        { lyrics: "dance", chords: "Am" },
        { lyrics: "and" },
        { lyrics: "now", chords: "F" },
        { lyrics: "I'm" },
        { lyrics: "singing" },
        { lyrics: "like" },
      ],
      [
        { lyrics: "Girl" },
        { lyrics: "you" },
        { lyrics: "know", chords: "G" },
        { lyrics: "I" },
        { lyrics: "want" },
        { lyrics: "your" },
        { lyrics: "love", chords: "Am" },
      ],
      [
        { lyrics: "Your" },
        { lyrics: "love" },
        { lyrics: "was" },
        { lyrics: "handmade", chords: "Dm" },
        { lyrics: "for" },
        { lyrics: "somebody" },
        { lyrics: "like" },
        { lyrics: "me", chords: "C" },
      ],
      [
        { lyrics: "Come", chords: "G" },
        { lyrics: "on" },
        { lyrics: "now" },
        { lyrics: "follow", chords: "F" },
        { lyrics: "my" },
        { lyrics: "lead" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "may" },
        { lyrics: "be", chords: "Am" },
        { lyrics: "crazy" },
        { lyrics: "don't" },
        { lyrics: "mind", chords: "C" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "Say", chords: "F" },
        { lyrics: "boy" },
        { lyrics: "let's" },
        { lyrics: "not" },
        { lyrics: "talk", chords: "G" },
        { lyrics: "too" },
        { lyrics: "much" },
      ],
      [
        { lyrics: "Grab" },
        { lyrics: "on" },
        { lyrics: "my", chords: "Dm" },
        { lyrics: "waist" },
        { lyrics: "and" },
        { lyrics: "put" },
        { lyrics: "that", chords: "C" },
        { lyrics: "body" },
        { lyrics: "on" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "Come" },
        { lyrics: "on" },
        { lyrics: "now" },
        { lyrics: "follow", chords: "G" },
        { lyrics: "my" },
        { lyrics: "lead" },
      ],
      [
        { lyrics: "Come" },
        { lyrics: "come" },
        { lyrics: "on" },
        { lyrics: "now", chords: "F" },
        { lyrics: "follow" },
        { lyrics: "my", chords: "Am" },
        { lyrics: "lead" },
      ],
      [
        { lyrics: "I'm" },
        { lyrics: "in", chords: "C" },
        { lyrics: "love" },
        { lyrics: "with" },
        { lyrics: "the", chords: "Dm" },
        { lyrics: "shape" },
        { lyrics: "of", chords: "G" },
        { lyrics: "you" },
      ],
      [
        { lyrics: "We", chords: "F" },
        { lyrics: "push" },
        { lyrics: "and" },
        { lyrics: "pull", chords: "Am" },
        { lyrics: "like" },
        { lyrics: "a", chords: "C" },
        { lyrics: "magnet" },
        { lyrics: "do" },
      ],
      [
        { lyrics: "Although" },
        { lyrics: "my", chords: "G" },
        { lyrics: "heart" },
        { lyrics: "is" },
        { lyrics: "falling", chords: "F" },
        { lyrics: "too" },
      ],
      [
        { lyrics: "I'm", chords: "Dm" },
        { lyrics: "in" },
        { lyrics: "love" },
        { lyrics: "with", chords: "C" },
        { lyrics: "your" },
        { lyrics: "body" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "last", chords: "F" },
        { lyrics: "night" },
        { lyrics: "you", chords: "Am" },
        { lyrics: "were" },
        { lyrics: "in" },
        { lyrics: "my" },
        { lyrics: "room" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now" },
        { lyrics: "my", chords: "G" },
        { lyrics: "bedsheets" },
        { lyrics: "smell", chords: "Dm" },
        { lyrics: "like" },
        { lyrics: "you" },
      ],
      [
        { lyrics: "Every", chords: "C" },
        { lyrics: "day" },
        { lyrics: "discovering", chords: "F" },
        { lyrics: "something" },
        { lyrics: "brand", chords: "Am" },
        { lyrics: "new" },
      ],
      [
        { lyrics: "I'm" },
        { lyrics: "in", chords: "G" },
        { lyrics: "love" },
        { lyrics: "with", chords: "C" },
        { lyrics: "your" },
        { lyrics: "body" },
      ],
    ],
  },
  {
    author: "Tones",
    name: "Dance Monkey",
    content: [
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "C" },
        { lyrics: "oh", chords: "Am" },
        { lyrics: "my" },
        { lyrics: "God" },
        { lyrics: "I" },
        { lyrics: "see", chords: "F" },
        { lyrics: "the" },
        { lyrics: "way", chords: "G" },
        { lyrics: "you" },
        { lyrics: "shine" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "your", chords: "Em" },
        { lyrics: "hand" },
        { lyrics: "my" },
        { lyrics: "dear" },
        { lyrics: "and", chords: "C" },
        { lyrics: "place" },
        { lyrics: "them" },
        { lyrics: "both" },
        { lyrics: "in", chords: "Am" },
        { lyrics: "mine" },
      ],
      [
        { lyrics: "You" },
        { lyrics: "know", chords: "F" },
        { lyrics: "you" },
        { lyrics: "stopped", chords: "G" },
        { lyrics: "me" },
        { lyrics: "dead" },
        { lyrics: "while" },
        { lyrics: "I" },
        { lyrics: "was" },
        { lyrics: "passing", chords: "C" },
        { lyrics: "by" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to", chords: "F" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "dance", chords: "G" },
        { lyrics: "just" },
        { lyrics: "one" },
        { lyrics: "more", chords: "C" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "Ooh", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "see" },
        { lyrics: "you", chords: "F" },
        { lyrics: "see", chords: "C" },
        { lyrics: "you" },
        { lyrics: "every" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "And", chords: "G" },
        { lyrics: "oh" },
        { lyrics: "my" },
        { lyrics: "I", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "I" },
        { lyrics: "like" },
        { lyrics: "your" },
        { lyrics: "style", chords: "F" },
      ],
      [
        { lyrics: "You", chords: "C" },
        { lyrics: "you" },
        { lyrics: "make", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "make", chords: "G" },
        { lyrics: "me" },
        { lyrics: "make", chords: "F" },
        { lyrics: "me" },
        { lyrics: "wanna" },
        { lyrics: "cry" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "C" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "dance" },
        { lyrics: "just", chords: "F" },
        { lyrics: "one" },
        { lyrics: "more" },
        { lyrics: "time", chords: "G" },
      ],
      [{ lyrics: "So", chords: "C" }, { lyrics: "they" }, { lyrics: "say" }],
      [
        { lyrics: '"Dance' },
        { lyrics: "for", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "dance" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "oh-oh", chords: "G" },
      ],
      [
        { lyrics: "I've" },
        { lyrics: "never", chords: "C" },
        { lyrics: "seen" },
        { lyrics: "anybody", chords: "Am" },
        { lyrics: "do" },
        { lyrics: "the" },
        { lyrics: "things" },
        { lyrics: "you" },
        { lyrics: "do", chords: "F" },
        { lyrics: "before" },
      ],
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "G" },
        { lyrics: '"Move' },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for", chords: "C" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for" },
        { lyrics: "me", chords: "Am" },
        { lyrics: "ay-ay" },
      ],
      [
        { lyrics: "And", chords: "F" },
        { lyrics: "when" },
        { lyrics: "you're", chords: "G" },
        { lyrics: "done" },
        { lyrics: "I'll" },
        { lyrics: "make" },
        { lyrics: "you" },
        { lyrics: "do" },
        { lyrics: "it", chords: "C" },
        { lyrics: "all" },
        { lyrics: "again" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "said", chords: "Am" },
        { lyrics: '"Oh' },
        { lyrics: "my" },
        { lyrics: "God" },
        { lyrics: "I", chords: "F" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "walking" },
        { lyrics: "by", chords: "G" },
      ],
      [
        { lyrics: "Take" },
        { lyrics: "my" },
        { lyrics: "hands", chords: "C" },
        { lyrics: "my" },
        { lyrics: "dear" },
        { lyrics: "and", chords: "Am" },
        { lyrics: "look" },
        { lyrics: "me" },
        { lyrics: "in" },
        { lyrics: "my", chords: "F" },
        { lyrics: "eyes" },
      ],
      [
        { lyrics: "Just" },
        { lyrics: "like", chords: "G" },
        { lyrics: "a" },
        { lyrics: "monkey" },
        { lyrics: "I've", chords: "C" },
        { lyrics: "been" },
        { lyrics: "dancing" },
        { lyrics: "my" },
        { lyrics: "whole", chords: "Am" },
        { lyrics: "life" },
      ],
      [
        { lyrics: "But" },
        { lyrics: "you" },
        { lyrics: "just", chords: "F" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see", chords: "G" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "C" },
        { lyrics: "just" },
        { lyrics: "one", chords: "Am" },
        { lyrics: "more" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "Ooh" },
        { lyrics: "I" },
        { lyrics: "see", chords: "F" },
        { lyrics: "you" },
        { lyrics: "see" },
        { lyrics: "you", chords: "G" },
        { lyrics: "see", chords: "C" },
        { lyrics: "you" },
        { lyrics: "every", chords: "Am" },
        { lyrics: "time" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "oh" },
        { lyrics: "my" },
        { lyrics: "I", chords: "F" },
        { lyrics: "I" },
        { lyrics: "I", chords: "G" },
        { lyrics: "like" },
        { lyrics: "your", chords: "C" },
        { lyrics: "style" },
      ],
      [
        { lyrics: "You", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "make" },
        { lyrics: "me" },
        { lyrics: "make", chords: "F" },
        { lyrics: "me" },
        { lyrics: "make", chords: "G" },
        { lyrics: "me" },
        { lyrics: "wanna" },
        { lyrics: "cry", chords: "C" },
      ],
      [
        { lyrics: "And" },
        { lyrics: "now", chords: "Am" },
        { lyrics: "I" },
        { lyrics: "beg" },
        { lyrics: "to" },
        { lyrics: "see" },
        { lyrics: "you" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "just" },
        { lyrics: "one", chords: "G" },
        { lyrics: "more" },
        { lyrics: "time" },
      ],
      [{ lyrics: "So", chords: "C" }, { lyrics: "they" }, { lyrics: "say" }],
      [
        { lyrics: '"Dance' },
        { lyrics: "for", chords: "Am" },
        { lyrics: "me" },
        { lyrics: "dance" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "dance", chords: "F" },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "oh-oh", chords: "G" },
      ],
      [
        { lyrics: "I've", chords: "C" },
        { lyrics: "never" },
        { lyrics: "seen", chords: "Am" },
        { lyrics: "anybody" },
        { lyrics: "do" },
        { lyrics: "the" },
        { lyrics: "things" },
        { lyrics: "you", chords: "F" },
        { lyrics: "do" },
        { lyrics: "before" },
      ],
      [
        { lyrics: "They" },
        { lyrics: "say", chords: "G" },
        { lyrics: '"Move' },
        { lyrics: "for" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for", chords: "C" },
        { lyrics: "me" },
        { lyrics: "move" },
        { lyrics: "for" },
        { lyrics: "me", chords: "Am" },
        { lyrics: "ay-ay" },
      ],
      [
        { lyrics: "And", chords: "F" },
        { lyrics: "when" },
        { lyrics: "you're", chords: "G" },
        { lyrics: "done" },
        { lyrics: "I'll" },
        { lyrics: "make" },
        { lyrics: "you" },
        { lyrics: "do" },
        { lyrics: "it", chords: "C" },
        { lyrics: "all" },
        { lyrics: "again" },
      ],
    ],
  },
  {
    author: "Drake",
    name: "One Dance",
    content: [
      [
        { lyrics: "Baby" },
        { lyrics: "I", chords: "C" },
        { lyrics: "like", chords: "Am" },
        { lyrics: "your" },
        { lyrics: "style", chords: "F" },
      ],
      [
        { lyrics: "Grips" },
        { lyrics: "on", chords: "G" },
        { lyrics: "your" },
        { lyrics: "waist", chords: "C" },
      ],
      [
        { lyrics: "Front" },
        { lyrics: "way" },
        { lyrics: "back", chords: "Am" },
        { lyrics: "way" },
      ],
      [
        { lyrics: "You", chords: "F" },
        { lyrics: "know" },
        { lyrics: "that", chords: "G" },
        { lyrics: "I" },
        { lyrics: "don't" },
        { lyrics: "play", chords: "C" },
      ],
      [
        { lyrics: "Streets" },
        { lyrics: "not" },
        { lyrics: "safe", chords: "Am" },
      ],
      [
        { lyrics: "But", chords: "F" },
        { lyrics: "I" },
        { lyrics: "never", chords: "G" },
        { lyrics: "run" },
        { lyrics: "away", chords: "C" },
      ],
      [
        { lyrics: "Even" },
        { lyrics: "when" },
        { lyrics: "I'm", chords: "Am" },
        { lyrics: "away" },
      ],
      [
        { lyrics: "OT" },
        { lyrics: "OT", chords: "F" },
        { lyrics: "there's" },
        { lyrics: "never" },
        { lyrics: "much", chords: "G" },
        { lyrics: "love" },
        { lyrics: "when", chords: "C" },
        { lyrics: "we" },
        { lyrics: "go" },
        { lyrics: "OT" },
      ],
      [
        { lyrics: "I", chords: "Am" },
        { lyrics: "pray" },
        { lyrics: "to" },
        { lyrics: "make" },
        { lyrics: "it", chords: "F" },
        { lyrics: "back" },
        { lyrics: "in" },
        { lyrics: "one", chords: "G" },
        { lyrics: "piece" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "pray", chords: "C" },
        { lyrics: "I", chords: "Am" },
        { lyrics: "pray" },
      ],
      [
        { lyrics: "That's", chords: "F" },
        { lyrics: "why" },
        { lyrics: "I" },
        { lyrics: "need", chords: "G" },
        { lyrics: "a" },
        { lyrics: "one" },
        { lyrics: "dance", chords: "C" },
      ],
      [
        { lyrics: "Got" },
        { lyrics: "a" },
        { lyrics: "Hennessy", chords: "Am" },
        { lyrics: "in" },
        { lyrics: "my" },
        { lyrics: "hand", chords: "F" },
      ],
      [
        { lyrics: "One" },
        { lyrics: "more", chords: "G" },
        { lyrics: "time" },
        { lyrics: "'fore" },
        { lyrics: "I" },
        { lyrics: "go", chords: "C" },
      ],
      [
        { lyrics: "Higher", chords: "Am" },
        { lyrics: "powers" },
        { lyrics: "taking", chords: "F" },
        { lyrics: "a" },
        { lyrics: "hold" },
        { lyrics: "on", chords: "G" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "need", chords: "C" },
        { lyrics: "a" },
        { lyrics: "one", chords: "Am" },
        { lyrics: "dance" },
      ],
      [
        { lyrics: "Got" },
        { lyrics: "a" },
        { lyrics: "Hennessy", chords: "F" },
        { lyrics: "in" },
        { lyrics: "my" },
        { lyrics: "hand", chords: "G" },
      ],
      [
        { lyrics: "One" },
        { lyrics: "more", chords: "C" },
        { lyrics: "time" },
        { lyrics: "'fore" },
        { lyrics: "I", chords: "Am" },
        { lyrics: "go" },
      ],
      [
        { lyrics: "Higher" },
        { lyrics: "powers", chords: "F" },
        { lyrics: "taking", chords: "G" },
        { lyrics: "a" },
        { lyrics: "hold" },
        { lyrics: "on", chords: "C" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "Baby" },
        { lyrics: "I", chords: "Am" },
        { lyrics: "like", chords: "F" },
        { lyrics: "your" },
        { lyrics: "style", chords: "G" },
      ],
      [
        { lyrics: "Strength", chords: "C" },
        { lyrics: "and" },
        { lyrics: "guidance", chords: "Am" },
      ],
      [
        { lyrics: "All" },
        { lyrics: "that", chords: "F" },
        { lyrics: "I'm" },
        { lyrics: "wishin'", chords: "G" },
        { lyrics: "for" },
        { lyrics: "my", chords: "C" },
        { lyrics: "friends" },
      ],
      [
        { lyrics: "Nobody", chords: "Am" },
        { lyrics: "makes" },
        { lyrics: "it", chords: "F" },
        { lyrics: "from" },
        { lyrics: "my", chords: "G" },
        { lyrics: "ends" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "had" },
        { lyrics: "to", chords: "C" },
        { lyrics: "bust", chords: "Am" },
        { lyrics: "up" },
        { lyrics: "the", chords: "F" },
        { lyrics: "silence" },
      ],
      [
        { lyrics: "You" },
        { lyrics: "know", chords: "G" },
        { lyrics: "you" },
        { lyrics: "gotta", chords: "C" },
        { lyrics: "stick" },
        { lyrics: "by", chords: "Am" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "Soon" },
        { lyrics: "as" },
        { lyrics: "you", chords: "F" },
        { lyrics: "see" },
        { lyrics: "the", chords: "G" },
        { lyrics: "text" },
        { lyrics: "reply", chords: "C" },
        { lyrics: "me" },
      ],
      [
        { lyrics: "I" },
        { lyrics: "don't" },
        { lyrics: "wanna", chords: "Am" },
        { lyrics: "spend" },
        { lyrics: "time", chords: "F" },
        { lyrics: "fighting" },
      ],
      [
        { lyrics: "We've" },
        { lyrics: "got", chords: "G" },
        { lyrics: "no" },
        { lyrics: "time", chords: "C" },
      ],
    ],
  },
  {
    author: "The Beatles",
    name: "Hey Jude",
    content: [
      [
        { lyrics: "Hey" },
        { lyrics: "Jude", chords: "C" },
        { lyrics: "don't", chords: "Am" },
        { lyrics: "make" },
        { lyrics: "it", chords: "F" },
        { lyrics: "bad" },
      ],
      [
        { lyrics: "Take", chords: "G" },
        { lyrics: "a" },
        { lyrics: "sad" },
        { lyrics: "song", chords: "C" },
        { lyrics: "and" },
        { lyrics: "make", chords: "Am" },
        { lyrics: "it" },
        { lyrics: "better", chords: "F" },
      ],
      [
        { lyrics: "Remember" },
        { lyrics: "to", chords: "G" },
        { lyrics: "let" },
        { lyrics: "her" },
        { lyrics: "into", chords: "C" },
        { lyrics: "your" },
        { lyrics: "heart" },
      ],
      [
        { lyrics: "Then", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "can", chords: "F" },
        { lyrics: "start" },
        { lyrics: "to" },
        { lyrics: "make", chords: "C" },
        { lyrics: "it" },
        { lyrics: "better", chords: "G" },
      ],
      [
        { lyrics: "Hey" },
        { lyrics: "Jude", chords: "F" },
        { lyrics: "don't" },
        { lyrics: "be" },
        { lyrics: "afraid", chords: "Am" },
      ],
      [
        { lyrics: "You", chords: "C" },
        { lyrics: "were" },
        { lyrics: "made", chords: "G" },
        { lyrics: "to" },
        { lyrics: "go" },
        { lyrics: "out", chords: "F" },
        { lyrics: "and" },
        { lyrics: "get", chords: "C" },
        { lyrics: "her" },
      ],
      [
        { lyrics: "The" },
        { lyrics: "minute", chords: "Am" },
        { lyrics: "you" },
        { lyrics: "let", chords: "F" },
        { lyrics: "her" },
        { lyrics: "under", chords: "G" },
        { lyrics: "your" },
        { lyrics: "skin" },
      ],
      [
        { lyrics: "Then", chords: "C" },
        { lyrics: "you" },
        { lyrics: "begin", chords: "Am" },
        { lyrics: "to" },
        { lyrics: "make", chords: "F" },
        { lyrics: "it" },
        { lyrics: "better" },
      ],
      [
        { lyrics: "And", chords: "G" },
        { lyrics: "anytime" },
        { lyrics: "you" },
        { lyrics: "feel", chords: "C" },
        { lyrics: "the" },
        { lyrics: "pain" },
      ],
      [
        { lyrics: "Hey" },
        { lyrics: "Jude", chords: "Am" },
        { lyrics: "refrain", chords: "F" },
      ],
      [
        { lyrics: "Don't" },
        { lyrics: "carry", chords: "C" },
        { lyrics: "the" },
        { lyrics: "world", chords: "G" },
        { lyrics: "upon", chords: "F" },
        { lyrics: "your" },
        { lyrics: "shoulders" },
      ],
      [
        { lyrics: "For", chords: "C" },
        { lyrics: "well" },
        { lyrics: "you" },
        { lyrics: "know" },
        { lyrics: "that", chords: "Am" },
        { lyrics: "it's" },
        { lyrics: "a" },
        { lyrics: "fool", chords: "F" },
        { lyrics: "who" },
        { lyrics: "plays" },
        { lyrics: "it", chords: "G" },
        { lyrics: "cool" },
      ],
      [
        { lyrics: "By", chords: "C" },
        { lyrics: "making" },
        { lyrics: "his" },
        { lyrics: "world", chords: "Am" },
        { lyrics: "a" },
        { lyrics: "little", chords: "F" },
        { lyrics: "colder" },
      ],
      [
        { lyrics: "Hey" },
        { lyrics: "Jude", chords: "G" },
        { lyrics: "don't" },
        { lyrics: "let", chords: "C" },
        { lyrics: "me" },
        { lyrics: "down" },
      ],
      [
        { lyrics: "You" },
        { lyrics: "have", chords: "Am" },
        { lyrics: "found" },
        { lyrics: "her", chords: "F" },
        { lyrics: "now" },
        { lyrics: "go", chords: "C" },
        { lyrics: "and" },
        { lyrics: "get", chords: "G" },
        { lyrics: "her" },
      ],
      [
        { lyrics: "Remember" },
        { lyrics: "to", chords: "Am" },
        { lyrics: "let" },
        { lyrics: "her", chords: "F" },
        { lyrics: "into" },
        { lyrics: "your", chords: "G" },
        { lyrics: "heart" },
      ],
      [
        { lyrics: "Then", chords: "C" },
        { lyrics: "you" },
        { lyrics: "can", chords: "Am" },
        { lyrics: "start", chords: "F" },
        { lyrics: "to" },
        { lyrics: "make", chords: "G" },
        { lyrics: "it", chords: "C" },
        { lyrics: "better" },
      ],
      [
        { lyrics: "So", chords: "Am" },
        { lyrics: "let" },
        { lyrics: "it" },
        { lyrics: "out", chords: "F" },
        { lyrics: "and" },
        { lyrics: "let" },
        { lyrics: "it", chords: "G" },
        { lyrics: "in" },
      ],
      [{ lyrics: "Hey", chords: "C" }, { lyrics: "Jude" }, { lyrics: "begin" }],
      [
        { lyrics: "You're", chords: "Am" },
        { lyrics: "waiting" },
        { lyrics: "for", chords: "F" },
        { lyrics: "someone" },
        { lyrics: "to", chords: "G" },
        { lyrics: "perform" },
        { lyrics: "with" },
      ],
      [
        { lyrics: "And", chords: "C" },
        { lyrics: "don't" },
        { lyrics: "you" },
        { lyrics: "know" },
        { lyrics: "that", chords: "Am" },
        { lyrics: "it's" },
        { lyrics: "just", chords: "F" },
        { lyrics: "you" },
      ],
      [
        { lyrics: "Hey", chords: "G" },
        { lyrics: "Jude", chords: "C" },
        { lyrics: "you'll" },
        { lyrics: "do" },
      ],
      [
        { lyrics: "The", chords: "Am" },
        { lyrics: "movement" },
        { lyrics: "you", chords: "F" },
        { lyrics: "need" },
        { lyrics: "is", chords: "G" },
        { lyrics: "on", chords: "C" },
        { lyrics: "your" },
        { lyrics: "shoulder" },
      ],
      [
        { lyrics: "Hey", chords: "Am" },
        { lyrics: "Jude" },
        { lyrics: "don't" },
        { lyrics: "make", chords: "F" },
        { lyrics: "it", chords: "G" },
        { lyrics: "bad" },
      ],
      [
        { lyrics: "Take", chords: "C" },
        { lyrics: "a" },
        { lyrics: "sad", chords: "Am" },
        { lyrics: "song" },
        { lyrics: "and", chords: "F" },
        { lyrics: "make", chords: "G" },
        { lyrics: "it" },
        { lyrics: "better" },
      ],
      [
        { lyrics: "Remember", chords: "C" },
        { lyrics: "to" },
        { lyrics: "let", chords: "Am" },
        { lyrics: "her" },
        { lyrics: "under", chords: "F" },
        { lyrics: "your" },
        { lyrics: "skin" },
      ],
      [
        { lyrics: "Then", chords: "G" },
        { lyrics: "you'll" },
        { lyrics: "begin", chords: "C" },
        { lyrics: "to" },
        { lyrics: "make", chords: "Am" },
        { lyrics: "it", chords: "F" },
      ],
      [
        { lyrics: "Better", chords: "G" },
        { lyrics: "better" },
        { lyrics: "better" },
        { lyrics: "better", chords: "C" },
        { lyrics: "better" },
        { lyrics: "better", chords: "Am" },
        { lyrics: "oh", chords: "F" },
      ],
    ],
  },
];

export default songs;
